env:
  global:
    - CC_TEST_REPORTER_ID=b0d803bc8521a63c141a7fae63d6cb620301f635383c121d6c90bed4f78f5ab6

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - pip install --upgrade pip
  - pip install -r requirements-test.txt .

script:
  - py.test --cov-report xml --cov=authoritah

after_script:
  - ./cc-test-reporter after-build -d --coverage-input-type coverage.py --exit-code $TRAVIS_TEST_RESULT
