env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - pip install --upgrade pip
  - pip install -r requirements-test.txt .

script:
  - py.test tests/

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT